import { type PortfolioPageData, PortfolioPositionKind, PortfolioPositionStatus } from "./types"

export function loadPortfolioPageData(): PortfolioPageData {
  return {
    summary: {
      activePositions: 4,
      claimableAmountUsd: 186.2,
      managerBalanceUsd: 1428.54,
      realizedPnlUsd: 92.8,
    },
    positions: [
      {
        id: "btc-up-29may",
        assetSymbol: "BTC",
        entryPriceLabel: "$108,400 strike",
        expiryLabel: "29 May · 16:00 UTC",
        kind: PortfolioPositionKind.Binary,
        outcomeLabel: "Up",
        pnlLabel: "+$48.20 unrealized",
        quantityLabel: "125.00 USDC at risk",
        settlementLabel: "Settles above $108,400",
        status: PortfolioPositionStatus.Active,
        valueLabel: "Potential payout $241.80",
      },
      {
        id: "btc-range-29may",
        assetSymbol: "BTC",
        entryPriceLabel: "$107,000 - $109,000",
        expiryLabel: "29 May · 16:00 UTC",
        kind: PortfolioPositionKind.Range,
        outcomeLabel: "Inside range",
        pnlLabel: "+$16.90 unrealized",
        quantityLabel: "80.00 USDC at risk",
        settlementLabel: "Pays if expiry spot lands inside range",
        status: PortfolioPositionStatus.Active,
        valueLabel: "Potential payout $156.40",
      },
      {
        id: "btc-up-26may",
        assetSymbol: "BTC",
        entryPriceLabel: "$106,500 strike",
        expiryLabel: "26 May · 12:00 UTC",
        kind: PortfolioPositionKind.Binary,
        outcomeLabel: "Up",
        pnlLabel: "Claim ready",
        quantityLabel: "65.00 USDC minted",
        settlementLabel: "Oracle settled in the money",
        status: PortfolioPositionStatus.Redeemable,
        valueLabel: "Claimable $121.20",
      },
      {
        id: "btc-down-24may",
        assetSymbol: "BTC",
        entryPriceLabel: "$103,800 strike",
        expiryLabel: "24 May · 08:00 UTC",
        kind: PortfolioPositionKind.Binary,
        outcomeLabel: "Down",
        pnlLabel: "+$27.70 realized",
        quantityLabel: "45.00 USDC redeemed",
        settlementLabel: "Claim completed",
        status: PortfolioPositionStatus.Settled,
        valueLabel: "Payout received $72.70",
      },
    ],
    activity: [
      {
        id: "activity-1",
        actionLabel: "Redeemed position",
        amountLabel: "+$72.70",
        assetSymbol: "BTC",
        detailLabel: "Binary Down payout received",
        timeLabel: "12m ago",
      },
      {
        id: "activity-2",
        actionLabel: "Minted range",
        amountLabel: "-$80.00",
        assetSymbol: "BTC",
        detailLabel: "Range position opened for 29 May expiry",
        timeLabel: "1h ago",
      },
      {
        id: "activity-3",
        actionLabel: "Minted binary",
        amountLabel: "-$125.00",
        assetSymbol: "BTC",
        detailLabel: "Up position opened above $108,400",
        timeLabel: "3h ago",
      },
    ],
  }
}
