// GENERATED by services/operator/src/sync-config.ts from the deployment
// manifest. Do not edit by hand — re-run `bun run sync-config` after a deploy.

export interface StrategyDeployment {
  managerId: string
  packageId: string
  strategyId: string
}

export interface CallItDeployment {
  arena: { arenaId: string; packageId: string }
  baseVault: { packageId: string; vaultId: string }
  keeperRewards: { packageId: string; vaultId: string }
  network: string
  strategies: {
    "bullish-upside": StrategyDeployment
    "hedged-plp": StrategyDeployment
    "plp-collar": StrategyDeployment
    "range-ladder": StrategyDeployment
    strangle: StrategyDeployment
  }
}

export const DEPLOYMENT: CallItDeployment = {
  arena: {
    arenaId: "0x04fa00e9e39489bde2f6e3e7144548557c9272db589cdad6c65755ab808e9a9c",
    packageId: "0x2feb9cafa30c952d2c8d8ba4a30b1c5ef74968c686b3c9c5f8db9ca6c6106075",
  },
  baseVault: {
    packageId: "0x9985416afd5e475727f8c2c8b407bfbdbbdfc94e3344a20f3ad3ace6e7f9f709",
    vaultId: "0x582b9a78622d39637896496e00a02ea122879c0f18ead1d693ddc86db2ce10e3",
  },
  keeperRewards: {
    packageId: "0xbe2ca72472f8c9e29d0fee940263fc5eb45363d0de19e959b23fddfc76b38811",
    vaultId: "0x8e248b2ab7bb397b8a7a0eaabf01e726534e9d82575901e77e4abe150085d799",
  },
  network: "testnet",
  strategies: {
  "bullish-upside": {
    packageId: "0x2ccd355090c569a7226d5c3879f0e4759efecbf2021f043e408ab48da2f65390",
    strategyId: "0xe3f3e28c7641304681f2e7034ec26e665ed6cf8d4326a6d36161dec679f02984",
    managerId: "0x20348b6480881e439c53c7d5bc4f0ae91c60f76a172cc3f7efba90b510a2909b",
  },
  "hedged-plp": {
    packageId: "0xc49064da43eaffcff2d5b20d504338e8b0ffbcd8d7fad1d80f4e79449e4488ab",
    strategyId: "0xa98235ae20ccb53dcbee80386dd1cfdc5e168130b584cd5b7ad3fe062bc7383d",
    managerId: "0x75a18f17d01388c228bb538aebe2e8599a6083ccedafcb49b0a5c16ce5e2a80b",
  },
  "plp-collar": {
    packageId: "0x82fa24a1f16ab1a9a637f3044492763faa342336dc135a436ed036a9d34fb10b",
    strategyId: "0xef73c8a9f7d2dd6e6b7f0a5c04e0cef834a975c29373c545c4fd1cad29ade7d5",
    managerId: "0x437ca89127fbbca624cac4ec0eb7c7bb90f35c21c720f6c64d4e3924470309e4",
  },
  "range-ladder": {
    packageId: "0x6d9c665ba628abd7c7070907bb0491d09164d6a1f94faa9c665e3b8157f5e059",
    strategyId: "0x397a558af354a61f3dd3cb47cf6e25c0cbe1d450be361ce73901c51420e36dfb",
    managerId: "0x92c155f3a5ed5a792eabae22f0ebbf62979981bdeaa689236d5e62787ef43933",
  },
  "strangle": {
    packageId: "0x757b2c37a5768576cf2eab55ce672fdd125d735a45f1fc0f4132bbc9cac581ad",
    strategyId: "0x39a943e090116cdab9331a6581319afb63c46f4647275d30f8b9be7c324ce62a",
    managerId: "0x8331294e867c3547ae6a7b16212de6137e98b0906ada9c6cad790f7eba15835f",
  },
  },
}
