// GENERATED by services/operator/src/sync-config.ts from the deployment
// manifest. Do not edit by hand — re-run `bun run sync-config` after a deploy.

export interface StrategyDeployment {
  managerId: string
  packageId: string
  strategyId: string
}

export interface CallItDeployment {
  arena: { arenaId: string; packageId: string }
  baseVault: { packageId: string; vaultId: string }
  keeperRewards: { packageId: string; vaultId: string }
  network: string
  strategies: {
    "bullish-upside": StrategyDeployment
    "hedged-plp": StrategyDeployment
    "plp-collar": StrategyDeployment
    "range-ladder": StrategyDeployment
    strangle: StrategyDeployment
  }
}

export const DEPLOYMENT: CallItDeployment = {
  arena: {
    arenaId: "0xda927248cef779d5af576962f03b0945e3db292b4153b171c4c9ea4e1df54e92",
    packageId: "0x86f8fd50525cf8aea274b2559886fd1b4bdf2a6c8d1b353ff053548eabdb0dac",
  },
  baseVault: {
    packageId: "0x68f736e0f30bf7a4881799a0cf77393f3fe881334703916f8ffc2c755a40f819",
    vaultId: "0x725808c6e223395dabf586de6ac3b9051a9c71c9767353bf51ec43b0d0c5789a",
  },
  keeperRewards: {
    packageId: "0x5377850cbe864c82594f68a59086fbdda2f5d022fd4f6a4d45a520ec30c52b23",
    vaultId: "0xa50e85c869c0aa8f49a57eff1d5bf02f1af77548f7be4296bcf201b33b3b328d",
  },
  network: "testnet",
  strategies: {
  "bullish-upside": {
    packageId: "0x44124c6f36ea35bce2e9d07c78fb5fb7bbbe929ef86bfe2022a3deee3a3e516e",
    strategyId: "0x7bb781a258940ace6f8f4ab2e11ae6bcc994e386dd8870e02d32c52bdcf6be26",
    managerId: "0x1595077ba74e466da5ba743d27c3e889d129576d798f7333e027ec12d24576ae",
  },
  "hedged-plp": {
    packageId: "0x1d31f6fc178655df407c27d431f15a54ff78db4c32cb554d0985c875475a73eb",
    strategyId: "0x34b006a8a45c7fda01964f25a4723e43c257b5e0c96a4ad780f24e96c61da8b0",
    managerId: "0xf1ea74e837c4f5efc79cc233c3cd71c3d5698bee70bdb1d23fad1ebcde1ea469",
  },
  "plp-collar": {
    packageId: "0xbc3679406f6130a881f8e32052135f62e266a28d5bf4cf63f71499eeec1a8666",
    strategyId: "0x4761f3b80dadc1e5b714980ad202db9b6914027f1453145419c0718eb867d98b",
    managerId: "0x3da65551d0dcfa6d0f383c7d8ab87f516c213030e64e16f208d988c143455e73",
  },
  "range-ladder": {
    packageId: "0x6cf1f7c7240bfabd34b5957184be36538192babde467d7590bad782a56c29503",
    strategyId: "0x15d70d726d875dc7d88b900e331a2ba761b16c627e3200bc67733ecb58d884ed",
    managerId: "0xfea3ae663621c79a60c67584e8d9f6f63a5e7147c4908d5003d0f7f5d649fe0e",
  },
  "strangle": {
    packageId: "0x2629511beba0667aa07519dcefbe91346e3fcfef2026b7288a2d069e0211876c",
    strategyId: "0xc140312aeebe986d9f838219a6f68d4897092f1ab18082f5f2d3e11f5d4de650",
    managerId: "0xdc2c44591940e1aebd2bde4e500667dba3ccb2a2f9179690dd10bbde2a6452ce",
  },
  },
}
