// Reads the on-chain deployment manifest (deployment.<network>.json, written by
// deploy.ts) and propagates the ids into the consuming services:
//   - web/src/lib/deployment.ts  (generated: the complete, typed source of truth)
//   - web/src/lib/config.ts      (patched: arena ids, base vault, BACKEND_URL)
//   - web/.env                   (patched/created: VITE_DYNAMIC_ENVIRONMENT_ID)
//   - services/backend/.env      (patched/created: ARENA_PACKAGE_ID/OBJECT_ID)
// Run after every deploy: `bun run sync-config`.

import { access, copyFile, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

import { logger } from "./logger.ts"

const DYNAMIC_ENV_ID = "981f0d75-a958-444d-8eb4-703aa3d30c18"

interface StrategyDeployment {
  adminCapId: string
  keeperCapId: string
  managerId: string
  packageId: string
  strategyId: string
}

interface DeploymentManifest {
  arena: { adminCapId: string; arenaId: string; packageId: string }
  baseVault: { capId: string; packageId: string; vaultId: string }
  bullishUpside: StrategyDeployment
  hedgedPlp: StrategyDeployment
  keeperRewards: { adminCapId: string; funded: boolean; packageId: string; vaultId: string }
  network: string
  operator: string
  plpCollar: StrategyDeployment
  rangeLadder: StrategyDeployment
  strangle: StrategyDeployment
}

function renderDeploymentModule(manifest: DeploymentManifest): string {
  // The web app keys strategies by kebab-case slug (also the URL segment); the
  // deployment manifest keeps the operator's camelCase field names. Translate here.
  const strategy = (label: string, value: StrategyDeployment) =>
    `  "${label}": {\n` +
    `    packageId: "${value.packageId}",\n` +
    `    strategyId: "${value.strategyId}",\n` +
    `    managerId: "${value.managerId}",\n` +
    `  },`

  return `// GENERATED by services/operator/src/sync-config.ts from the deployment
// manifest. Do not edit by hand — re-run \`bun run sync-config\` after a deploy.

export interface StrategyDeployment {
  managerId: string
  packageId: string
  strategyId: string
}

export interface CallItDeployment {
  arena: { arenaId: string; packageId: string }
  baseVault: { packageId: string; vaultId: string }
  keeperRewards: { packageId: string; vaultId: string }
  network: string
  strategies: {
    "bullish-upside": StrategyDeployment
    "hedged-plp": StrategyDeployment
    "plp-collar": StrategyDeployment
    "range-ladder": StrategyDeployment
    strangle: StrategyDeployment
  }
}

export const DEPLOYMENT: CallItDeployment = {
  arena: {
    arenaId: "${manifest.arena.arenaId}",
    packageId: "${manifest.arena.packageId}",
  },
  baseVault: {
    packageId: "${manifest.baseVault.packageId}",
    vaultId: "${manifest.baseVault.vaultId}",
  },
  keeperRewards: {
    packageId: "${manifest.keeperRewards.packageId}",
    vaultId: "${manifest.keeperRewards.vaultId}",
  },
  network: "${manifest.network}",
  strategies: {
${strategy("bullish-upside", manifest.bullishUpside)}
${strategy("hedged-plp", manifest.hedgedPlp)}
${strategy("plp-collar", manifest.plpCollar)}
${strategy("range-ladder", manifest.rangeLadder)}
${strategy("strangle", manifest.strangle)}
  },
}
`
}

// Replace the string literal of `export const NAME = "..."`, preserving the
// existing formatting (single- or multi-line). Throws if the constant is absent
// so a renamed/removed constant surfaces loudly instead of silently no-op'ing.
function setExport(source: string, name: string, value: string): string {
  const pattern = new RegExp(`(export const ${name}(?:: [\\w<>\\[\\] ]+)? =\\s*)"[^"]*"`)
  if (!pattern.test(source)) {
    throw new Error(`config.ts is missing 'export const ${name} = "..."'`)
  }
  return source.replace(pattern, `$1"${value}"`)
}

// Upsert a KEY=value line in a .env body, preserving everything else.
function setEnv(body: string, key: string, value: string): string {
  const pattern = new RegExp(`^${key}=.*$`, "m")
  const line = `${key}=${value}`
  if (pattern.test(body)) {
    return body.replace(pattern, line)
  }
  return `${body.trimEnd()}\n${line}\n`
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file)
    return true
  } catch {
    return false
  }
}

async function main(): Promise<void> {
  const network = process.env.SUI_NETWORK?.trim() || "testnet"
  const repoRoot = path.resolve(import.meta.dir, "../../..")
  const manifestPath = path.join(import.meta.dir, `../deployment.${network}.json`)
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as DeploymentManifest

  // 1. Generated web deployment module (complete, typed source of truth).
  const webDeployment = path.join(repoRoot, "web/src/lib/deployment.ts")
  await writeFile(webDeployment, renderDeploymentModule(manifest))
  logger.info({ file: webDeployment }, "wrote generated deployment module")

  // 2. Patch the global constants the arena flow + backend reads use today.
  // BACKEND_URL / KEEPER_API_URL are env-driven now (VITE_* in web/.env*), so
  // they're not patched here — only the manifest-derived ids are.
  const webConfigPath = path.join(repoRoot, "web/src/lib/config.ts")
  let webConfig = await readFile(webConfigPath, "utf8")
  webConfig = setExport(webConfig, "ARENA_PACKAGE_ID", manifest.arena.packageId)
  webConfig = setExport(webConfig, "ARENA_OBJECT_ID", manifest.arena.arenaId)
  webConfig = setExport(webConfig, "BASE_VAULT_ID", manifest.baseVault.vaultId)
  await writeFile(webConfigPath, webConfig)
  logger.info({ file: webConfigPath }, "patched web config constants")

  // 3. web/.env — VITE_DYNAMIC_ENVIRONMENT_ID for the Dynamic provider.
  const webEnvPath = path.join(repoRoot, "web/.env")
  const webEnvBody = (await exists(webEnvPath)) ? await readFile(webEnvPath, "utf8") : ""
  await writeFile(webEnvPath, setEnv(webEnvBody, "VITE_DYNAMIC_ENVIRONMENT_ID", DYNAMIC_ENV_ID))
  logger.info({ file: webEnvPath }, "patched web .env")

  // 4. services/backend/.env — arena ids (create from example if missing).
  const backendEnvPath = path.join(repoRoot, "services/backend/.env")
  if (!(await exists(backendEnvPath))) {
    await copyFile(path.join(repoRoot, "services/backend/.env.example"), backendEnvPath)
  }
  let backendEnv = await readFile(backendEnvPath, "utf8")
  backendEnv = setEnv(backendEnv, "ARENA_PACKAGE_ID", manifest.arena.packageId)
  backendEnv = setEnv(backendEnv, "ARENA_OBJECT_ID", manifest.arena.arenaId)
  await writeFile(backendEnvPath, backendEnv)
  logger.info({ file: backendEnvPath }, "patched backend .env arena ids")

  logger.info({ network }, "sync-config complete")
}

main().catch((error: unknown) => {
  logger.error({ error: error instanceof Error ? error.message : String(error) }, "sync-config failed")
  process.exit(1)
})
