/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteRouteImport } from './routes/strategies/route'
import { Route as ShieldRouteRouteImport } from './routes/shield/route'
import { Route as RiskRouteRouteImport } from './routes/risk/route'
import { Route as RangeLadderRouteRouteImport } from './routes/range-ladder/route'
import { Route as PortfolioRouteRouteImport } from './routes/portfolio/route'
import { Route as MarketsRouteRouteImport } from './routes/markets/route'
import { Route as LeaderboardRouteRouteImport } from './routes/leaderboard/route'
import { Route as EarnRouteRouteImport } from './routes/earn/route'
import { Route as ArenaRouteRouteImport } from './routes/arena/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShieldIndexRouteImport } from './routes/shield/index'
import { Route as RangeLadderIndexRouteImport } from './routes/range-ladder/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as MarketsOracleIdRouteRouteImport } from './routes/markets/$oracleId/route'

const StrategiesRouteRoute = StrategiesRouteRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldRouteRoute = ShieldRouteRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRouteRoute = RiskRouteRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeLadderRouteRoute = RangeLadderRouteRouteImport.update({
  id: '/range-ladder',
  path: '/range-ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRouteRoute = MarketsRouteRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRouteRoute = LeaderboardRouteRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRouteRoute = EarnRouteRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRouteRoute = ArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldIndexRoute = ShieldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShieldRouteRoute,
} as any)
const RangeLadderIndexRoute = RangeLadderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RangeLadderRouteRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRouteRoute,
} as any)
const MarketsOracleIdRouteRoute = MarketsOracleIdRouteRouteImport.update({
  id: '/$oracleId',
  path: '/$oracleId',
  getParentRoute: () => MarketsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRoute
  '/earn': typeof EarnRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/markets': typeof MarketsRouteRouteWithChildren
  '/portfolio': typeof PortfolioRouteRoute
  '/range-ladder': typeof RangeLadderRouteRouteWithChildren
  '/risk': typeof RiskRouteRoute
  '/shield': typeof ShieldRouteRouteWithChildren
  '/strategies': typeof StrategiesRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/markets/': typeof MarketsIndexRoute
  '/range-ladder/': typeof RangeLadderIndexRoute
  '/shield/': typeof ShieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRoute
  '/earn': typeof EarnRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/portfolio': typeof PortfolioRouteRoute
  '/risk': typeof RiskRouteRoute
  '/strategies': typeof StrategiesRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/markets': typeof MarketsIndexRoute
  '/range-ladder': typeof RangeLadderIndexRoute
  '/shield': typeof ShieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRoute
  '/earn': typeof EarnRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/markets': typeof MarketsRouteRouteWithChildren
  '/portfolio': typeof PortfolioRouteRoute
  '/range-ladder': typeof RangeLadderRouteRouteWithChildren
  '/risk': typeof RiskRouteRoute
  '/shield': typeof ShieldRouteRouteWithChildren
  '/strategies': typeof StrategiesRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/markets/': typeof MarketsIndexRoute
  '/range-ladder/': typeof RangeLadderIndexRoute
  '/shield/': typeof ShieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/earn'
    | '/leaderboard'
    | '/markets'
    | '/portfolio'
    | '/range-ladder'
    | '/risk'
    | '/shield'
    | '/strategies'
    | '/markets/$oracleId'
    | '/markets/'
    | '/range-ladder/'
    | '/shield/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/earn'
    | '/leaderboard'
    | '/portfolio'
    | '/risk'
    | '/strategies'
    | '/markets/$oracleId'
    | '/markets'
    | '/range-ladder'
    | '/shield'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/earn'
    | '/leaderboard'
    | '/markets'
    | '/portfolio'
    | '/range-ladder'
    | '/risk'
    | '/shield'
    | '/strategies'
    | '/markets/$oracleId'
    | '/markets/'
    | '/range-ladder/'
    | '/shield/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRouteRoute: typeof ArenaRouteRoute
  EarnRouteRoute: typeof EarnRouteRoute
  LeaderboardRouteRoute: typeof LeaderboardRouteRoute
  MarketsRouteRoute: typeof MarketsRouteRouteWithChildren
  PortfolioRouteRoute: typeof PortfolioRouteRoute
  RangeLadderRouteRoute: typeof RangeLadderRouteRouteWithChildren
  RiskRouteRoute: typeof RiskRouteRoute
  ShieldRouteRoute: typeof ShieldRouteRouteWithChildren
  StrategiesRouteRoute: typeof StrategiesRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield': {
      id: '/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof ShieldRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range-ladder': {
      id: '/range-ladder'
      path: '/range-ladder'
      fullPath: '/range-ladder'
      preLoaderRoute: typeof RangeLadderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield/': {
      id: '/shield/'
      path: '/'
      fullPath: '/shield/'
      preLoaderRoute: typeof ShieldIndexRouteImport
      parentRoute: typeof ShieldRouteRoute
    }
    '/range-ladder/': {
      id: '/range-ladder/'
      path: '/'
      fullPath: '/range-ladder/'
      preLoaderRoute: typeof RangeLadderIndexRouteImport
      parentRoute: typeof RangeLadderRouteRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRouteRoute
    }
    '/markets/$oracleId': {
      id: '/markets/$oracleId'
      path: '/$oracleId'
      fullPath: '/markets/$oracleId'
      preLoaderRoute: typeof MarketsOracleIdRouteRouteImport
      parentRoute: typeof MarketsRouteRoute
    }
  }
}

interface MarketsRouteRouteChildren {
  MarketsOracleIdRouteRoute: typeof MarketsOracleIdRouteRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteRouteChildren: MarketsRouteRouteChildren = {
  MarketsOracleIdRouteRoute: MarketsOracleIdRouteRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteRouteWithChildren = MarketsRouteRoute._addFileChildren(
  MarketsRouteRouteChildren,
)

interface RangeLadderRouteRouteChildren {
  RangeLadderIndexRoute: typeof RangeLadderIndexRoute
}

const RangeLadderRouteRouteChildren: RangeLadderRouteRouteChildren = {
  RangeLadderIndexRoute: RangeLadderIndexRoute,
}

const RangeLadderRouteRouteWithChildren =
  RangeLadderRouteRoute._addFileChildren(RangeLadderRouteRouteChildren)

interface ShieldRouteRouteChildren {
  ShieldIndexRoute: typeof ShieldIndexRoute
}

const ShieldRouteRouteChildren: ShieldRouteRouteChildren = {
  ShieldIndexRoute: ShieldIndexRoute,
}

const ShieldRouteRouteWithChildren = ShieldRouteRoute._addFileChildren(
  ShieldRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRouteRoute: ArenaRouteRoute,
  EarnRouteRoute: EarnRouteRoute,
  LeaderboardRouteRoute: LeaderboardRouteRoute,
  MarketsRouteRoute: MarketsRouteRouteWithChildren,
  PortfolioRouteRoute: PortfolioRouteRoute,
  RangeLadderRouteRoute: RangeLadderRouteRouteWithChildren,
  RiskRouteRoute: RiskRouteRoute,
  ShieldRouteRoute: ShieldRouteRouteWithChildren,
  StrategiesRouteRoute: StrategiesRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
