/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteRouteImport } from './routes/strategies/route'
import { Route as RiskRouteRouteImport } from './routes/risk/route'
import { Route as PortfolioRouteRouteImport } from './routes/portfolio/route'
import { Route as MarketsRouteRouteImport } from './routes/markets/route'
import { Route as LeaderboardRouteRouteImport } from './routes/leaderboard/route'
import { Route as KeeperRouteRouteImport } from './routes/keeper/route'
import { Route as EarnRouteRouteImport } from './routes/earn/route'
import { Route as ArenaRouteRouteImport } from './routes/arena/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as ArenaIndexRouteImport } from './routes/arena/index'
import { Route as StrategiesStrategyIdRouteRouteImport } from './routes/strategies/$strategyId/route'
import { Route as MarketsOracleIdRouteRouteImport } from './routes/markets/$oracleId/route'
import { Route as ArenaCallIdRouteRouteImport } from './routes/arena/$callId/route'
import { Route as ArenaCreatorHandleRouteRouteImport } from './routes/arena/creator/$handle/route'

const StrategiesRouteRoute = StrategiesRouteRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRouteRoute = RiskRouteRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRouteRoute = PortfolioRouteRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRouteRoute = MarketsRouteRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRouteRoute = LeaderboardRouteRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KeeperRouteRoute = KeeperRouteRouteImport.update({
  id: '/keeper',
  path: '/keeper',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRouteRoute = EarnRouteRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRouteRoute = ArenaRouteRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StrategiesRouteRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRouteRoute,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const StrategiesStrategyIdRouteRoute =
  StrategiesStrategyIdRouteRouteImport.update({
    id: '/$strategyId',
    path: '/$strategyId',
    getParentRoute: () => StrategiesRouteRoute,
  } as any)
const MarketsOracleIdRouteRoute = MarketsOracleIdRouteRouteImport.update({
  id: '/$oracleId',
  path: '/$oracleId',
  getParentRoute: () => MarketsRouteRoute,
} as any)
const ArenaCallIdRouteRoute = ArenaCallIdRouteRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => ArenaRouteRoute,
} as any)
const ArenaCreatorHandleRouteRoute = ArenaCreatorHandleRouteRouteImport.update({
  id: '/creator/$handle',
  path: '/creator/$handle',
  getParentRoute: () => ArenaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/earn': typeof EarnRouteRoute
  '/keeper': typeof KeeperRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/markets': typeof MarketsRouteRouteWithChildren
  '/portfolio': typeof PortfolioRouteRoute
  '/risk': typeof RiskRouteRoute
  '/strategies': typeof StrategiesRouteRouteWithChildren
  '/arena/$callId': typeof ArenaCallIdRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRouteRoute
  '/arena/': typeof ArenaIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/arena/creator/$handle': typeof ArenaCreatorHandleRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/earn': typeof EarnRouteRoute
  '/keeper': typeof KeeperRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/portfolio': typeof PortfolioRouteRoute
  '/risk': typeof RiskRouteRoute
  '/arena/$callId': typeof ArenaCallIdRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRouteRoute
  '/arena': typeof ArenaIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
  '/arena/creator/$handle': typeof ArenaCreatorHandleRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteRouteWithChildren
  '/earn': typeof EarnRouteRoute
  '/keeper': typeof KeeperRouteRoute
  '/leaderboard': typeof LeaderboardRouteRoute
  '/markets': typeof MarketsRouteRouteWithChildren
  '/portfolio': typeof PortfolioRouteRoute
  '/risk': typeof RiskRouteRoute
  '/strategies': typeof StrategiesRouteRouteWithChildren
  '/arena/$callId': typeof ArenaCallIdRouteRoute
  '/markets/$oracleId': typeof MarketsOracleIdRouteRoute
  '/strategies/$strategyId': typeof StrategiesStrategyIdRouteRoute
  '/arena/': typeof ArenaIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/arena/creator/$handle': typeof ArenaCreatorHandleRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/earn'
    | '/keeper'
    | '/leaderboard'
    | '/markets'
    | '/portfolio'
    | '/risk'
    | '/strategies'
    | '/arena/$callId'
    | '/markets/$oracleId'
    | '/strategies/$strategyId'
    | '/arena/'
    | '/markets/'
    | '/strategies/'
    | '/arena/creator/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/earn'
    | '/keeper'
    | '/leaderboard'
    | '/portfolio'
    | '/risk'
    | '/arena/$callId'
    | '/markets/$oracleId'
    | '/strategies/$strategyId'
    | '/arena'
    | '/markets'
    | '/strategies'
    | '/arena/creator/$handle'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/earn'
    | '/keeper'
    | '/leaderboard'
    | '/markets'
    | '/portfolio'
    | '/risk'
    | '/strategies'
    | '/arena/$callId'
    | '/markets/$oracleId'
    | '/strategies/$strategyId'
    | '/arena/'
    | '/markets/'
    | '/strategies/'
    | '/arena/creator/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRouteRoute: typeof ArenaRouteRouteWithChildren
  EarnRouteRoute: typeof EarnRouteRoute
  KeeperRouteRoute: typeof KeeperRouteRoute
  LeaderboardRouteRoute: typeof LeaderboardRouteRoute
  MarketsRouteRoute: typeof MarketsRouteRouteWithChildren
  PortfolioRouteRoute: typeof PortfolioRouteRoute
  RiskRouteRoute: typeof RiskRouteRoute
  StrategiesRouteRoute: typeof StrategiesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keeper': {
      id: '/keeper'
      path: '/keeper'
      fullPath: '/keeper'
      preLoaderRoute: typeof KeeperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof StrategiesRouteRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRouteRoute
    }
    '/arena/': {
      id: '/arena/'
      path: '/'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/strategies/$strategyId': {
      id: '/strategies/$strategyId'
      path: '/$strategyId'
      fullPath: '/strategies/$strategyId'
      preLoaderRoute: typeof StrategiesStrategyIdRouteRouteImport
      parentRoute: typeof StrategiesRouteRoute
    }
    '/markets/$oracleId': {
      id: '/markets/$oracleId'
      path: '/$oracleId'
      fullPath: '/markets/$oracleId'
      preLoaderRoute: typeof MarketsOracleIdRouteRouteImport
      parentRoute: typeof MarketsRouteRoute
    }
    '/arena/$callId': {
      id: '/arena/$callId'
      path: '/$callId'
      fullPath: '/arena/$callId'
      preLoaderRoute: typeof ArenaCallIdRouteRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
    '/arena/creator/$handle': {
      id: '/arena/creator/$handle'
      path: '/creator/$handle'
      fullPath: '/arena/creator/$handle'
      preLoaderRoute: typeof ArenaCreatorHandleRouteRouteImport
      parentRoute: typeof ArenaRouteRoute
    }
  }
}

interface ArenaRouteRouteChildren {
  ArenaCallIdRouteRoute: typeof ArenaCallIdRouteRoute
  ArenaIndexRoute: typeof ArenaIndexRoute
  ArenaCreatorHandleRouteRoute: typeof ArenaCreatorHandleRouteRoute
}

const ArenaRouteRouteChildren: ArenaRouteRouteChildren = {
  ArenaCallIdRouteRoute: ArenaCallIdRouteRoute,
  ArenaIndexRoute: ArenaIndexRoute,
  ArenaCreatorHandleRouteRoute: ArenaCreatorHandleRouteRoute,
}

const ArenaRouteRouteWithChildren = ArenaRouteRoute._addFileChildren(
  ArenaRouteRouteChildren,
)

interface MarketsRouteRouteChildren {
  MarketsOracleIdRouteRoute: typeof MarketsOracleIdRouteRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteRouteChildren: MarketsRouteRouteChildren = {
  MarketsOracleIdRouteRoute: MarketsOracleIdRouteRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteRouteWithChildren = MarketsRouteRoute._addFileChildren(
  MarketsRouteRouteChildren,
)

interface StrategiesRouteRouteChildren {
  StrategiesStrategyIdRouteRoute: typeof StrategiesStrategyIdRouteRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
}

const StrategiesRouteRouteChildren: StrategiesRouteRouteChildren = {
  StrategiesStrategyIdRouteRoute: StrategiesStrategyIdRouteRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
}

const StrategiesRouteRouteWithChildren = StrategiesRouteRoute._addFileChildren(
  StrategiesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRouteRoute: ArenaRouteRouteWithChildren,
  EarnRouteRoute: EarnRouteRoute,
  KeeperRouteRoute: KeeperRouteRoute,
  LeaderboardRouteRoute: LeaderboardRouteRoute,
  MarketsRouteRoute: MarketsRouteRouteWithChildren,
  PortfolioRouteRoute: PortfolioRouteRoute,
  RiskRouteRoute: RiskRouteRoute,
  StrategiesRouteRoute: StrategiesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
